language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra
    - add-on

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
deploy:
  provider: releases
  api_key:
    secure: CULs4/id7b+bXo8+Om/LJcPjnvQ3RWeS7y7OohVM0/R4PHEO9wFMRVchHXHaTwkGgSAjnDkreDL9fxrbaHx9hGaBOgsewS9JfhdmSlpdCUO1d30r3hGuHGCSRQRD72LQkWSqdEi6TgrXLavZfp8aH8U42khkmCFsd/+dJrND3hI=
  file: app/build/outputs/apk/app-debug.apk
  on:
    repo: PlayRTC/PlayRTC-Android-Tutorial-SimpleChat
  skip_cleanup: true
  on:
    tags: true
